# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 6-angular/email-ui

pool:
  vmImage: ubuntu-latest

variables:
  appDirectory: 6-angular/email-ui

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: npm install
  workingDirectory: $(appDirectory)

- script: npx ng build
  displayName: ng build
  workingDirectory: $(appDirectory)

- script: npx ng lint
  displayName: ng lint
  workingDirectory: $(appDirectory)

- script: npx ng test --browsers ChromeHeadless --no-watch --code-coverage
  displayName: ng test
  workingDirectory: $(appDirectory)

# ng e2e... exercise for the reader

- task: SonarCloudPrepare@1
  displayName: sonar prepare analysis
  inputs:
    SonarCloud: 'sonarcloud-escalonn'
    organization: '2102-feb08-net'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '2102-feb08-net_trainer-code-email-ui'
    cliProjectName: 'Email UI'
    cliSources: '$(appDirectory)/src'
    extraProperties: 'sonar.javascript.lcov.reportPaths=$(appDirectory)/coverage/email-ui/lcov.info'

- task: SonarCloudAnalyze@1
  displayName: sonar run analysis

- task: SonarCloudPublish@1
  displayName: sonar publish analysis result
  inputs:
    pollingTimeoutSec: '300'
